services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa
    volumes:
      - medusa-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  medusa-postgres-data:
